ui:
  default_width: 450
inputs_def:
  - handle: zip_file
    json_schema:
      type: string
      ui:widget: save
  - handle: zip_dir
    json_schema:
      type: string
      ui:widget: dir
    nullable: true
    value:
  - handle: password
    json_schema:
      type: string
    value:
    nullable: true
outputs_def:
  - handle: output
    description: Output
    json_schema:
      type: string
      ui:widget: file
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
title: Extract ZIP
icon: ":carbon:zip:"
